# Generated by Django 4.1.6 on 2023-02-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50000)),
                ('excrept', models.CharField(max_length=1000)),
                ('slug', models.SlugField(verbose_name='')),
                ('img', models.ImageField(upload_to=None, verbose_name='')),
                ('date', models.DateField(verbose_name='')),
            ],
        ),
    ]
