# Generated by Django 4.1.6 on 2023-02-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ayhaga',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
